// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlRmdpGilen-YpQVaWjWwaXj35HhtNz4',
    appId: '1:378227139760:android:6b6a153270269fa75e0775',
    messagingSenderId: '378227139760',
    projectId: 'nrityasetu',
    storageBucket: 'nrityasetu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvx-yfj09nxcQWn87um7l__CdpuOmpP60',
    appId: '1:378227139760:ios:1c6c6f337669d68b5e0775',
    messagingSenderId: '378227139760',
    projectId: 'nrityasetu',
    storageBucket: 'nrityasetu.firebasestorage.app',
    iosBundleId: 'com.example.nrityaSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvx-yfj09nxcQWn87um7l__CdpuOmpP60',
    appId: '1:378227139760:ios:1c6c6f337669d68b5e0775',
    messagingSenderId: '378227139760',
    projectId: 'nrityasetu',
    storageBucket: 'nrityasetu.firebasestorage.app',
    iosBundleId: 'com.example.nrityaSetu',
  );
}
